import { useState, useMemo } from "react";
import { DatasetRow, StatsConfig } from "@/types/dataset";
import { ColumnAnalysis } from "@/lib/csvAnalyzer";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Switch } from "@/components/ui/switch";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Database,
  FileSpreadsheet,
  Hash,
  Calendar,
  Tag,
  TrendingUp,
  Info,
  Edit2,
  Save,
  X,
} from "lucide-react";

interface SmartStatsProps {
  rows: DatasetRow[];
  columns: ColumnAnalysis[];
  datasetName: string;
  statsConfigs?: StatsConfig[];
  onUpdateStats?: (configs: StatsConfig[]) => void;
}

interface StatCard {
  label: string;
  value: string | number;
  icon: React.ReactNode;
  iconType: 'database' | 'file' | 'tag' | 'calendar' | 'hash' | 'trend';
  description: string;
  highlight?: boolean;
}

const ICON_MAP = {
  database: Database,
  file: FileSpreadsheet,
  tag: Tag,
  calendar: Calendar,
  hash: Hash,
  trend: TrendingUp,
};

function truncateValue(value: string, maxLength: number = 20): string {
  if (value.length <= maxLength) return value;
  return value.slice(0, maxLength) + "...";
}

export function SmartStats({ 
  rows, 
  columns, 
  datasetName,
  statsConfigs,
  onUpdateStats,
}: SmartStatsProps) {
  const [editOpen, setEditOpen] = useState(false);
  const [editingConfigs, setEditingConfigs] = useState<StatsConfig[]>([]);

  const autoGeneratedStats = useMemo(() => {
    const cards: StatCard[] = [];

    // Total records
    cards.push({
      label: "Total de Registros",
      value: rows.length.toLocaleString("pt-BR"),
      icon: <Database className="w-5 h-5" />,
      iconType: 'database',
      description: "Número total de linhas no dataset",
    });

    // Total columns
    cards.push({
      label: "Campos",
      value: columns.length,
      icon: <FileSpreadsheet className="w-5 h-5" />,
      iconType: 'file',
      description: `Colunas: ${columns.map(c => c.displayName).slice(0, 5).join(", ")}${columns.length > 5 ? "..." : ""}`,
    });

    // Find most interesting categorical column
    const categoryColumn = columns.find(c => c.isCategorical && c.uniqueValues > 1 && c.uniqueValues <= 20);
    if (categoryColumn) {
      const counts: Record<string, number> = {};
      rows.forEach(row => {
        const val = String(row.row_data[categoryColumn.name] || "");
        if (val) counts[val] = (counts[val] || 0) + 1;
      });
      
      const mostCommon = Object.entries(counts)
        .sort((a, b) => b[1] - a[1])[0];
      
      if (mostCommon) {
        cards.push({
          label: `Principal ${categoryColumn.displayName}`,
          value: mostCommon[0],
          icon: <Tag className="w-5 h-5" />,
          iconType: 'tag',
          description: `${mostCommon[1]} registros (${((mostCommon[1] / rows.length) * 100).toFixed(1)}%)`,
          highlight: true,
        });
      }
    }

    // Find date range if there's a date column
    const dateColumn = columns.find(c => c.isDate);
    if (dateColumn) {
      const dates = rows
        .map(r => r.row_data[dateColumn.name])
        .filter(d => d)
        .map(d => String(d))
        .sort();
      
      if (dates.length > 0) {
        cards.push({
          label: "Período",
          value: dates.length > 1 ? `${dates[0]} a ${dates[dates.length - 1]}` : dates[0],
          icon: <Calendar className="w-5 h-5" />,
          iconType: 'calendar',
          description: `Baseado na coluna: ${dateColumn.displayName}`,
        });
      }
    }

    // Unique values count for an important column
    const uniqueColumn = columns.find(c => 
      !c.isIdentifier && 
      c.isCategorical &&
      c.uniqueValues > 1 && 
      c.uniqueValues < rows.length * 0.8
    );
    if (uniqueColumn && cards.length < 5) {
      cards.push({
        label: `${uniqueColumn.displayName} Únicos`,
        value: uniqueColumn.uniqueValues.toLocaleString("pt-BR"),
        icon: <Hash className="w-5 h-5" />,
        iconType: 'hash',
        description: `Valores distintos na coluna ${uniqueColumn.name}`,
      });
    }

    return cards.slice(0, 5);
  }, [rows, columns]);

  // Use saved configs or auto-generated
  const displayStats = useMemo(() => {
    if (statsConfigs && statsConfigs.length > 0) {
      return statsConfigs
        .filter(c => c.enabled)
        .map(config => {
          const IconComponent = ICON_MAP[config.icon] || Database;
          return {
            label: config.label,
            value: config.value,
            icon: <IconComponent className="w-5 h-5" />,
            iconType: config.icon,
            description: config.description,
            highlight: false,
          };
        });
    }
    return autoGeneratedStats;
  }, [statsConfigs, autoGeneratedStats]);

  const handleOpenEdit = () => {
    // Initialize with current configs or auto-generated
    const configs = statsConfigs && statsConfigs.length > 0 
      ? statsConfigs 
      : autoGeneratedStats.map(s => ({
          label: s.label,
          value: String(s.value),
          icon: s.iconType,
          description: s.description,
          enabled: true,
        }));
    setEditingConfigs(configs);
    setEditOpen(true);
  };

  const handleUpdateConfig = (index: number, field: keyof StatsConfig, value: string | boolean) => {
    setEditingConfigs(prev => {
      const updated = [...prev];
      updated[index] = { ...updated[index], [field]: value };
      return updated;
    });
  };

  const handleSave = () => {
    if (onUpdateStats) {
      onUpdateStats(editingConfigs);
    }
    setEditOpen(false);
  };

  return (
    <>
      <div className="relative">
        {onUpdateStats && (
          <div className="absolute -top-2 -right-2 z-10">
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    variant="outline"
                    size="icon"
                    className="h-8 w-8 rounded-full bg-card shadow-sm"
                    onClick={handleOpenEdit}
                  >
                    <Edit2 className="w-4 h-4" />
                  </Button>
                </TooltipTrigger>
                <TooltipContent>Editar estatísticas</TooltipContent>
              </Tooltip>
            </TooltipProvider>
          </div>
        )}
        
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">
          {displayStats.map((stat, index) => (
            <TooltipProvider key={index}>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Card 
                    className={`border-border cursor-help transition-all hover:shadow-md hover:border-primary/30 ${
                      stat.highlight ? 'ring-2 ring-primary/20' : ''
                    }`}
                  >
                    <CardContent className="p-4">
                      <div className="flex items-start justify-between">
                        <div className="p-2 rounded-lg bg-primary/10 text-primary">
                          {stat.icon}
                        </div>
                        <Info className="w-3 h-3 text-muted-foreground" />
                      </div>
                      <div className="mt-3">
                        <p className="text-2xl font-bold text-foreground truncate" title={String(stat.value)}>
                          {truncateValue(String(stat.value), 15)}
                        </p>
                        <p className="text-sm text-muted-foreground truncate" title={stat.label}>
                          {truncateValue(stat.label, 18)}
                        </p>
                      </div>
                    </CardContent>
                  </Card>
                </TooltipTrigger>
                <TooltipContent side="bottom" className="max-w-xs">
                  <p className="font-medium">{stat.label}</p>
                  <p className="text-sm font-bold">{stat.value}</p>
                  <p className="text-xs text-muted-foreground mt-1">{stat.description}</p>
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          ))}
        </div>
      </div>

      {/* Edit Stats Dialog */}
      <Dialog open={editOpen} onOpenChange={setEditOpen}>
        <DialogContent className="sm:max-w-[500px]">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Edit2 className="w-5 h-5" />
              Editar Estatísticas
            </DialogTitle>
          </DialogHeader>
          
          <ScrollArea className="h-[400px] border rounded-md">
            <div className="space-y-4 p-4">
              {editingConfigs.map((config, idx) => (
                <div key={idx} className="p-4 bg-muted/30 rounded-lg space-y-3">
                  <div className="flex items-center justify-between">
                    <Label className="text-sm font-medium">Card {idx + 1}</Label>
                    <div className="flex items-center gap-2">
                      <Label htmlFor={`enabled-${idx}`} className="text-xs">Ativo</Label>
                      <Switch
                        id={`enabled-${idx}`}
                        checked={config.enabled}
                        onCheckedChange={(val) => handleUpdateConfig(idx, 'enabled', val)}
                      />
                    </div>
                  </div>
                  
                  <div className="grid grid-cols-2 gap-3">
                    <div className="space-y-1">
                      <Label className="text-xs">Título</Label>
                      <Input
                        value={config.label}
                        onChange={(e) => handleUpdateConfig(idx, 'label', e.target.value)}
                        placeholder="Título do card"
                      />
                    </div>
                    <div className="space-y-1">
                      <Label className="text-xs">Valor</Label>
                      <Input
                        value={config.value}
                        onChange={(e) => handleUpdateConfig(idx, 'value', e.target.value)}
                        placeholder="Valor exibido"
                      />
                    </div>
                  </div>
                  
                  <div className="space-y-1">
                    <Label className="text-xs">Descrição (tooltip)</Label>
                    <Input
                      value={config.description}
                      onChange={(e) => handleUpdateConfig(idx, 'description', e.target.value)}
                      placeholder="Descrição ao passar o mouse"
                    />
                  </div>
                </div>
              ))}
            </div>
          </ScrollArea>

          <div className="flex justify-end gap-2 pt-2">
            <Button variant="outline" onClick={() => setEditOpen(false)}>
              <X className="w-4 h-4 mr-2" />
              Cancelar
            </Button>
            <Button onClick={handleSave}>
              <Save className="w-4 h-4 mr-2" />
              Salvar
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}